### ISSUE TITLE
Function names (custom or built-in) not showing up

### ISSUE THREAD

**Issue by cthielen** [derekr/php.sugar#9] opened 2009-04-24 16:16 UTC
This is Espresso 1.0.4:

$result = mysql_query("a query");

will be displayed in Espresso as:

$result = ("a query");

unless I put a space between mysql_query and ("a query");

Although the function is parsed correctly as it appears in the "DOM" navigator on the right.

Also, declaring functions, eg

function do_something($var) {

does not show the function name at all, regardless of spacing, it always displays as

function ($var) {

Please fix this soon, this makes Espresso unusable for PHP purposes.

**Comment by donut** [comment] 2009-04-26 17:36
How can I reproduce this? Are you talking about the automatic codesense popup? In what context is this happening? Because I can type out `$result = mysql_query("a query");` and Espresso wont erase what I've typed.

**Comment by derekr** [comment] 2009-04-28 01:02
This seems to be resolved with the latest version of Espresso.

**Closed as completed** 2009-04-28 01:02 UTC
